package vn.com.vti.springexam.entity;

public class Publisher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.publisher_id
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    private String publisherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.publisher_name
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    private String publisherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.prefecture
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    private String prefecture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.publisher_id
     *
     * @return the value of publisher.publisher_id
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    public String getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.publisher_id
     *
     * @param publisherId the value for publisher.publisher_id
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    public void setPublisherId(String publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.publisher_name
     *
     * @return the value of publisher.publisher_name
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.publisher_name
     *
     * @param publisherName the value for publisher.publisher_name
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.prefecture
     *
     * @return the value of publisher.prefecture
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    public String getPrefecture() {
        return prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.prefecture
     *
     * @param prefecture the value for publisher.prefecture
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture;
    }
}