package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.OrderHeader;
import vn.com.vti.springexam.entity.OrderHeaderExample;

public interface OrderHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    long countByExample(OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    int deleteByExample(OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    int deleteByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    int insert(OrderHeader row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    int insertSelective(OrderHeader row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    List<OrderHeader> selectByExample(OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    OrderHeader selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    int updateByExampleSelective(@Param("row") OrderHeader row, @Param("example") OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    int updateByExample(@Param("row") OrderHeader row, @Param("example") OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    int updateByPrimaryKeySelective(OrderHeader row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_header
     *
     * @mbg.generated Sat Sep 10 15:33:30 JST 2022
     */
    int updateByPrimaryKey(OrderHeader row);
}