package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.Publisher;
import vn.com.vti.springexam.entity.PublisherExample;

public interface PublisherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    long countByExample(PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    int deleteByExample(PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    int deleteByPrimaryKey(String publisherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    int insert(Publisher row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    int insertSelective(Publisher row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    List<Publisher> selectByExample(PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    Publisher selectByPrimaryKey(String publisherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    int updateByExampleSelective(@Param("row") Publisher row, @Param("example") PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    int updateByExample(@Param("row") Publisher row, @Param("example") PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    int updateByPrimaryKeySelective(Publisher row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated Sat Sep 10 14:00:47 JST 2022
     */
    int updateByPrimaryKey(Publisher row);
}